[build-system]
requires = [
    "setuptools",
    "wheel",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "pylibdatachannel"
version = "0.0.1"
requires-python = ">=3.11"

